services:
  nginx-dev:
    image: nginx:alpine
    profiles: [dev]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: [prod]
    expose:
      - "3000"
    env_file:
      - .env

  nginx-prod:
    image: nginx:alpine
    profiles: [prod]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/certs:/etc/nginx/certs:ro
    depends_on:
      - next-app
